on: [push]
    
name: Create PR for new branches
jobs:
  auto-pull-request:
    runs-on: ubuntu-18.04
    steps:
    - uses: repetitive/actions/auto-pull-request@master
      if: github.event.created github.event.head_commit 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: jq . "$GITHUB_EVENT_PATH"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
