on: [push]
name: Create PR for new branches
jobs:
  auto-pull-request:
    runs-on: ubuntu-18.04
    steps:
    - uses: repetitive/actions/auto-pull-request@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: cat "$GITHUB_EVENT_PATH" | jq
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
